#!/bin/bash

cat /etc/os-release

#sahve .sh file always
#after all this, to run this shell type ./nameoffile and press enter
#dont forget to give all execute permissons to the file by typing chmod a+x filename
